### ISSUE TITLE
Checking if a germ set is "amplificationally complete" (AC) takes a long time

### ISSUE THREAD

**Issue by ampolloreno** [pyGSTio/pyGSTi#24]
In the example germ generation notebook, checking if a 1Q germ set is AC seems to be fine, but for 2Q it takes a while. (I can add more quantitative statements in a bit.)

**Comment by bbloo** [comment]
Also addressed in #29

**Comment by enielse** [comment]
The suggested replacement, and several other similar ones, have been implemented in pyGSTi version 0.9.4.  Checks for amplification completeness can be performed using 
```
pygsti.alg.test_germ_list_infl(gateset, germsToTest)
```
Note that germ testing for AC-ness is still not parallel, i.e. it still can only use one CPU at once.  This is a future update we're thinking about but haven't implemented yet.
